# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# profile_curvature.py
# Created on: 2017-09-27 18:16:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: profile_curvature <curve> <pro_curve> <plan_curve> <Input_raster_or_constant_value_2> <Input_raster_or_constant_value_2__2_> <pprocurve> <nprocurve> <Z_factor>
# Description:
# ---------------------------------------------------------------------------
# Import arcpy module
import arcpy
import os
from arcpy import env
from arcpy.sa import Con
from arcpy.sa import *
import time; t0 = time.time()
import sys
arcpy.CheckOutExtension("Spatial")#Make sure spatial analyst is activated.

################################################################################
#Set working directory.
drive = 'X'
root_dir = drive + ":\PhD\junk"; os.chdir(root_dir)
curvature_files = 'curvature_files'
filename = 'mar_84_dem'

#Adjustable parameters.
Z_factor = "1"
range_len = 4 #This is the numer of times you want the loop to iterate through
                #different minumum and maximum value thresholds. Because Python
                #indexes from 0, the number of files you create will always be
                #1 less than this value.
minprocurve = -1
maxprocurve = 1

delete_ancillary_files = 'no' # Either yes or no.

################################################################################
# Automatically set directory paths and input file paths.
DEM = os.path.join(root_dir,  filename) #Input DEM.
out_folder = os.path.join(root_dir, curvature_files)
os.mkdir(out_folder)

#------------------------------------------------------------------------------#
#Main program.
for i in range(1,range_len):
    print 'profile curvature ' + '+/- ' + str(i)
    min = str(i * minprocurve)#Minimum.
    max = str(i * maxprocurve)#Maximum.
    base = 'curvature' + str(i)
    curve = os.path.join(root_dir, base) #Input DEM.
    pro_curve = os.path.join(out_folder, 'pro' + filename[:3] + str(i))#Output profile curvature raster.
    pprocurve = os.path.join(out_folder, 'p' + 'pro' + filename[:3] + str(i))#p==positive and corresponds to max, above.
    mpprocurve = os.path.join(out_folder, 'm' + 'p' + 'pro' + filename[:3] + str(i))
    nprocurve = os.path.join(out_folder, 'n' + 'pro' + filename[:3] + str(i))#n==negative and corresponds to min, above.
    mnprocurve = os.path.join(out_folder, 'm' + 'n' + 'pro' + filename[:3] + str(i))
    p_plus_n = os.path.join(out_folder, 'n' + 'p' + 'pro' + filename[:3] + str(i))#Combining max and min filtered rasters.
    filtprocurve = os.path.join(out_folder, 'f' + 'pro' + filename[:3] + str(i))
    inverse = os.path.join(out_folder, 'inv' + 'pro' + filename[:3] + str(i))
    #nullprocurve = os.path.join(out_folder, 'null' + 'pro' + filename)
    pfiltprocurve = os.path.join(out_folder, 'p' + 'f' + 'pro' + filename[:3] + str(i))
    scaled_procurve = os.path.join(root_dir, filename[:6] + '_'+ 'sc' + 'pro' + str(i))
    arcpy.gp.Curvature_sa(DEM, curve, Z_factor, pro_curve); time.sleep(2)
    arcpy.gp.GreaterThanEqual_sa(pro_curve, max, pprocurve); time.sleep(2)
    arcpy.gp.Times_sa(pprocurve, max, mpprocurve);time.sleep(2)
    arcpy.gp.LessThanEqual_sa(pro_curve, min, nprocurve);time.sleep(2)
    arcpy.gp.Times_sa(nprocurve, min, mnprocurve);time.sleep(2)
    arcpy.gp.Plus_sa(pprocurve, nprocurve, p_plus_n);time.sleep(2)
    arcpy.gp.Minus_sa("1", p_plus_n, inverse);time.sleep(2)
    #arcpy.gp.SetNull_sa(inverse, "1", nullprocurve, "")
    arcpy.gp.Times_sa(inverse, pro_curve, filtprocurve);time.sleep(2)
    arcpy.gp.Plus_sa(mpprocurve, filtprocurve, pfiltprocurve);time.sleep(2)
    arcpy.gp.Plus_sa(mnprocurve, pfiltprocurve, scaled_procurve);time.sleep(2)
    print 'Sleeping for 1 second...'
    time.sleep(1)
    arcpy.Delete_management(pro_curve, "")
    arcpy.Delete_management(pprocurve, "")
    arcpy.Delete_management(nprocurve, "")
    arcpy.Delete_management(curve, "")
    arcpy.Delete_management(p_plus_n, "")
    arcpy.Delete_management(inverse, "")
    arcpy.Delete_management(mpprocurve, "")
    arcpy.Delete_management(mnprocurve, "")
    arcpy.Delete_management(filtprocurve, "")
    arcpy.Delete_management(pfiltprocurve, "")

#------------------------------------------------------------------------------#
#Clean up unwanted data.
time.sleep(1)
os.chdir(out_folder)
if delete_ancillary_files == 'yes':
    os.chdir(out_folder)
    for (dirpath, dirnames, filenames) in os.walk('.'):
        for file in filenames:
            print 'this file will be deleted ' + '' + file
            arcpy.Delete_management(file)

    for (dirpath, dirnames, filenames) in os.walk('.'):
        for dir in dirnames:
            print dir
            print "This directory will be deleted " + str(dir)
            arcpy.Delete_management(dir)
else:
    print 'Keeping all files.'
    exit()#This just stops the script running if not deleting ancillary data.

os.chdir(root_dir)
print 'Deleting this folder' + ' - ' + out_folder; os.rmdir(out_folder)
#------------------------------------------------------------------------------#
print ""
print "Time taken:"
print "hours: %i, minutes: %i, seconds: %i" %(int((time.time()-t0)/3600), int(((time.time()-t0)%3600)/60), int((time.time()-t0)%60))


