# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# profile_curvature.py
# Created on: 2017-09-27 18:16:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: profile_curvature <curve> <pro_curve> <plan_curve> <Input_raster_or_constant_value_2> <Input_raster_or_constant_value_2__2_> <pprocurve> <nprocurve> <Z_factor>
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
from arcpy import env
from arcpy.sa import Con
from arcpy.sa import *
import time; t0 = time.time()
import sys
arcpy.CheckOutExtension("Spatial")#Make sure spatial analyst is activated.

################################################################################
#Basic inputs and outputs.
DEM = "C:\\PhD\\junk\\mary463" #Input DEM.

################################################################################
#Outputs.
curve = "C:\\PhD\\junk\\curve" #Output curvature raster.
pro_curve = "C:\\PhD\\junk\\pro_curve"#Output profile curvature raster.
pprocurve = "C:\\PhD\\junk\\pprocurve"#p==positive and corresponds to max, above.
nprocurve = "C:\\PhD\\junk\\nprocurve"#n==negative and corresponds to min, above.
p_plus_n = "C:\\PhD\\junk\\p_plus_n"#Combining max and min filtered rasters.
filtprocurve = "C:\\PhD\\junk\\filtprocurve"
inverse = "C:\\PhD\\junk\\inverse"
nullprocurve = "C:\\PhD\\junk\\nullprocurve"

################################################################################
#Adjustable parameters.
minprocurve = "-3.0"#Minimum.
maxprocurve = "3.0"#Maximum.
Z_factor = "1"

################################################################################
#Fixed values.
invert = "1"
nullvalue = "1"

################################################################################
#Main program.
arcpy.gp.Curvature_sa(DEM, curve, Z_factor, pro_curve)
arcpy.gp.GreaterThanEqual_sa(pro_curve, maxprocurve, pprocurve)
arcpy.gp.LessThanEqual_sa(pro_curve, minprocurve, nprocurve)
arcpy.gp.Plus_sa(pprocurve, nprocurve, p_plus_n)
arcpy.gp.Times_sa(p_plus_n, pro_curve, filtprocurve)
arcpy.gp.Minus_sa(invert, p_plus_n, inverse)
arcpy.gp.SetNull_sa(inverse, nullvalue, nullprocurve, "")

################################################################################
#Clean up redundant files.
arcpy.Delete_management(pprocurve, "")
arcpy.Delete_management(nprocurve, "")
arcpy.Delete_management(curve, "")
arcpy.Delete_management(inverse, "")

################################################################################
print ""
print "Time taken:"
print "hours: %i, minutes: %i, seconds: %i" %(int((time.time()-t0)/3600), int(((time.time()-t0)%3600)/60), int((time.time()-t0)%60))


