# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# sink_depth.py
# Created on: 2017-09-13 10:01:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: sink_depth <Output_drop_raster> <mary_km_km2_tif> <FlowDir_mary_km1_tif> <Sink_FlowDir_ma1_tif> <Watersh_FlowDir1_tif> <ZonalSt_Watersh1_tif> <ZonalFi_Watersh1_tif> <Minus_ZonalFi_W1_tif> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Output_drop_raster = arcpy.GetParameterAsText(0)

mary_km_km2_tif = arcpy.GetParameterAsText(1)
if mary_km_km2_tif == '#' or not mary_km_km2_tif:
    mary_km_km2_tif = "D:\\PhD\\reef_gis\\Mary\\mary_km_km2.tif" # provide a default value if unspecified

FlowDir_mary_km1_tif = arcpy.GetParameterAsText(2)
if FlowDir_mary_km1_tif == '#' or not FlowDir_mary_km1_tif:
    FlowDir_mary_km1_tif = "D:\\PhD\\reef_gis\\Mary\\FlowDir_mary_km1.tif" # provide a default value if unspecified

Sink_FlowDir_ma1_tif = arcpy.GetParameterAsText(3)
if Sink_FlowDir_ma1_tif == '#' or not Sink_FlowDir_ma1_tif:
    Sink_FlowDir_ma1_tif = "D:\\PhD\\reef_gis\\Mary\\Sink_FlowDir_ma1.tif" # provide a default value if unspecified

Watersh_FlowDir1_tif = arcpy.GetParameterAsText(4)
if Watersh_FlowDir1_tif == '#' or not Watersh_FlowDir1_tif:
    Watersh_FlowDir1_tif = "D:\\PhD\\reef_gis\\Mary\\Watersh_FlowDir1.tif" # provide a default value if unspecified

ZonalSt_Watersh1_tif = arcpy.GetParameterAsText(5)
if ZonalSt_Watersh1_tif == '#' or not ZonalSt_Watersh1_tif:
    ZonalSt_Watersh1_tif = "D:\\PhD\\reef_gis\\Mary\\ZonalSt_Watersh1.tif" # provide a default value if unspecified

ZonalFi_Watersh1_tif = arcpy.GetParameterAsText(6)
if ZonalFi_Watersh1_tif == '#' or not ZonalFi_Watersh1_tif:
    ZonalFi_Watersh1_tif = "D:\\PhD\\reef_gis\\Mary\\ZonalFi_Watersh1.tif" # provide a default value if unspecified

Minus_ZonalFi_W1_tif = arcpy.GetParameterAsText(7)
if Minus_ZonalFi_W1_tif == '#' or not Minus_ZonalFi_W1_tif:
    Minus_ZonalFi_W1_tif = "D:\\PhD\\reef_gis\\Mary\\Minus_ZonalFi_W1.tif" # provide a default value if unspecified

# Local variables:
Statistics_type = "MINIMUM"

# Process: Flow Direction
arcpy.gp.FlowDirection_sa(mary_km_km2_tif, FlowDir_mary_km1_tif, "NORMAL", Output_drop_raster)

# Process: Sink
arcpy.gp.Sink_sa(FlowDir_mary_km1_tif, Sink_FlowDir_ma1_tif)

# Process: Watershed
arcpy.gp.Watershed_sa(FlowDir_mary_km1_tif, Sink_FlowDir_ma1_tif, Watersh_FlowDir1_tif, "VALUE")

# Process: Zonal Fill
arcpy.gp.ZonalFill_sa(Watersh_FlowDir1_tif, mary_km_km2_tif, ZonalFi_Watersh1_tif)

# Process: Zonal Statistics
arcpy.gp.ZonalStatistics_sa(Watersh_FlowDir1_tif, "VALUE", mary_km_km2_tif, ZonalSt_Watersh1_tif, Statistics_type, "DATA")

# Process: Minus
arcpy.gp.Minus_sa(ZonalFi_Watersh1_tif, ZonalSt_Watersh1_tif, Minus_ZonalFi_W1_tif)

