# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# stream_order.py
# Created on: 2017-08-19 14:12:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: stream_order <Expand_raste1> <rastercalc1> <StreamO_rast1> <rastercalc> <Output_accumulation_raster> <Output_flow_direction_raster> <Fill_don_501> <don_50>
# Description:
# ---------------------------------------------------------------------------

#Imports.

import arcpy
import os
from arcpy import env
from arcpy.sa import Con
from arcpy.sa import *
import time; t0 = time.time()
import sys
arcpy.CheckOutExtension("Spatial")#Make sure spatial analyst is activated.

################################################################################
#Set the working directory.

root_dir = (r'X:\\PhD\\Junk')
os.chdir(root_dir)

################################################################################
#Setup local variables.

input_dem = "X:\\PhD\\5m_DEM\\don_50" # provide a default value if unspecified
Output_drop_raster = ""
Method_of_stream_ordering = "STRAHLER"
expand = "2"
fill_dem = os.path.join(root_dir, input_dem[-6:] + 'f')
flow_dir = os.path.join(root_dir, input_dem[-6:] +'dir')
flow_acc = os.path.join(root_dir, input_dem[-6:] +'fa')
streams = os.path.join(root_dir, input_dem[-6:] +'str')
stream_order = os.path.join(root_dir, input_dem[-6:] +'ord')
filt_stream_order = os.path.join(root_dir, input_dem[-6:] +'f_ord')
null_filt_stream_order = os.path.join(root_dir, input_dem[-6:] +'nf_ord')
expand_filt_streams = os.path.join(root_dir, input_dem[-6:] +'ef_ord')

################################################################################


# Process: Fill
arcpy.gp.Fill_sa(input_dem, fill_dem, ""); print 'fill works'

# Process: Flow Direction
arcpy.gp.FlowDirection_sa(fill_dem, flow_dir, "NORMAL", Output_drop_raster); print 'flow direction works'

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(flow_dir, flow_acc, "", "FLOAT"); print 'flow accumulation works'

flow_acc_rast = arcpy.Raster(flow_acc); print 'flow accumulation raster saved'

# Process: Raster Calculator
strms  = Con(flow_acc_rast >= 1000,1,0); print 'Raster calculator for streams => 1000 works'

stream = strms.save(streams); print 'stream raster saved'

# Process: Stream Order
arcpy.gp.StreamOrder_sa(streams, flow_dir, stream_order, Method_of_stream_ordering); print 'stream orders work'

stream_ord_rast = arcpy.Raster(stream_order); print 'stream order raster saved'

# Process: Raster Calculator (2)
flt_strm_ord = Con(stream_ord_rast >= 3,1,0); print 'stream order => 3 filtered out'

fil_or_st = flt_strm_ord.save(filt_stream_order); print 'filtered stream orders saved'

fil_or_st_rast = arcpy.Raster(filt_stream_order);

null_strm_ord = SetNull(fil_or_st_rast == 0, fil_or_st_rast)

nul_or_st = null_strm_ord.save(null_filt_stream_order); print 'nulled filtered stream orders saved'

# Process: Expand
arcpy.gp.Expand_sa(null_filt_stream_order, expand_filt_streams, expand, "1")


print ""
print "Time taken: " "hours: %i, minutes: %i, seconds: %i" %(int((time.time()-t0)/3600), int(((time.time()-t0)%3600)/60), int((time.time()-t0)%60))

