# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# training_shapes.py
# Created on: 2017-09-25 19:31:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: training_shapes <Ra_shp>
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
from arcpy import env
from arcpy.sa import Con
from arcpy.sa import *
import time; t0 = time.time()
import sys
arcpy.CheckOutExtension("Spatial")#Make sure spatial analyst is activated.

################################################################################

# Local variables:
in_raster = "C:\\PhD\\junk\\order_1_2"
diss_shp = "C:\\PhD\\junk\\Rad.shp"
init_shp = "C:\\PhD\\junk\\RasterT_order_11.shp" # provide a default value if unspecified

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(in_raster, init_shp, "SIMPLIFY", "VALUE")

# Process: Dissolve
arcpy.Dissolve_management(init_shp, diss_shp, "", "", "MULTI_PART", "DISSOLVE_LINES")

