# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# windows.py
# Created on: 2017-06-26 15:28:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: windows <fitz_f12_tif> <Foc_test>
# Description:
# ---------------------------------------------------------------------------

# Imports
import arcpy
from arcpy import env
from arcpy.sa import Con
from arcpy.sa import *
import os
import time; t0 = time.time()
import sys


arcpy.CheckOutExtension("Spatial")#Make sure spatial analyst is activated.

root_dir = (r'C:\\PhD\\junk')#Set the working directory.

os.chdir(root_dir)

in_rast = "C:\\PhD\\junk\\mary463" # provide a default value if unspecified

# Local variables:
shape = 'Rectangle ' #Name desired shape exactly with one space before closing quotes.
units = 'CELL' # or 'MAP', no space after
mean = "MEAN" #Can be any of the acceptable operations depending on data type (float or int)
mean_threshold = -0.1
stdev_threshold = -0.5
standard_deviation = "STD"
Ignore_NoData_in_calculations = "true" #or change to 'false'
iteration_factor = 5 #This is the value to adjust the wondow size for each iteration.
range_len = 3 #This is the numer of times you want the loop to iterate through different window sizes. Because Python indexes from 0, the number of files you create will always be 1 less than this value.

for i in range(1,range_len):
    in_height = i * iteration_factor #Specify window height.
    h = str(in_height)#
    height = h + ' '
    in_width = i * iteration_factor #Specify window width.
    w = str(in_width)
    width = w + ' '
    mean_out = in_rast[-6:-5] + '_' + 'm' + '_'  + str(i)
    stdev_out = in_rast[-6:-5] + '_' + 's' + '_'  + str(i)
    new_m = os.path.join(root_dir,mean_out)
    new_s = os.path.join(root_dir,stdev_out)
    n = shape + height + width + units;
    Neighborhood = str(n)
    print ('Window specifications', Neighborhood)
    print ('mean raster', new_m)
    print ('standard deviation raster', new_s)
    # Process: Focal Statistics
    arcpy.gp.FocalStatistics_sa(in_rast, new_m, Neighborhood, mean, Ignore_NoData_in_calculations)
    arcpy.gp.FocalStatistics_sa(in_rast, new_s, Neighborhood, standard_deviation, Ignore_NoData_in_calculations)

    #Local variables
    Location = root_dir
    stdev_f1 =stdev_out + '_r'
    mean_f1 =mean_out + '_r'
    outName_stdev = os.path.join(root_dir, stdev_f1)
    outName_mean = os.path.join(root_dir, mean_f1)
    outFolder = Location
    env.workspace = outFolder
    win_mean = arcpy.gp.Minus_sa(in_rast, new_m, outName_mean)
    win_std = arcpy.gp.Divide_sa(win_mean, new_s, outName_stdev)
    final_mean_mask = os.path.join(root_dir, in_rast[-6:-5] + 'f_m' + str(i))
    mean_thold= arcpy.gp.LessThanEqual_sa(win_mean, mean_threshold, final_mean_mask)
    final_std_mask = os.path.join(root_dir, in_rast[-6:-5] + 'f_s'+ str(i))
    std_thold = arcpy.gp.LessThanEqual_sa(win_mean, mean_threshold, final_std_mask)

    #Next do LessThanEqual with constant value -0.1 (creates 0,1 mask)
    #Then need to multiply this over mean and stdec diff rasters
    final_mean = os.path.join(root_dir, in_rast[-6:-5] + 'fim'+ str(i))
    arcpy.gp.Times_sa(final_mean_mask, outName_mean, final_mean)

    final_std = os.path.join(root_dir, in_rast[-6:-5] + 'fis'+ str(i))
    arcpy.gp.Times_sa(final_std_mask, outName_stdev, final_std)

    #filt_m = arcpy.Raster(final_mean)
    #filt_s = arcpy.Raster(final_std)
    #bool_m = SetNull(filt_m == 0, 1)
    #bool_s = SetNull(filt_s == 0, 1)
    #mask_mean = os.path.join(root_dir, in_rast[-6:] + 'b_m'+ str(i))
    #mask_stdev = os.path.join(root_dir, in_rast[-6:] + 'b_s'+ str(i))
    #bool_m.save(mask_mean)
    #bool_s.save(mask_stdev)
    #arcpy.Delete_management(new_m)
    #arcpy.Delete_management(new_s)
    #arcpy.Delete_management(outName_stdev)
    #arcpy.Delete_management(outName_mean)
    #arcpy.Delete_management(final_mean)
    #arcpy.Delete_management(final_std)

print ""
print "Time taken: " "hours: %i, minutes: %i, seconds: %i" %(int((time.time()-t0)/3600), int(((time.time()-t0)%3600)/60), int((time.time()-t0)%60))

